jobs:
  flint:
    name: Flint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm flint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm lint:knip
  lint_packages:
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm lint:packages
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm tsc -b
      - run: pnpm run test
  build_site:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm -r build

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
