jobs:
  flint:
    name: Flint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build
      - run: pnpm run -r build # Build packages/site
      - run: pnpm run flint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build
      - run: pnpm run -r prebuild # Generate packages/site/.astro without a full build.
      - run: pnpm run lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run build # Knip requires all exports to be generated.
      - run: pnpm run lint:knip
  lint_packages:
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:packages
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0 # required so origin/main can be diffed
      - uses: ./.github/actions/prepare
      - name: Cache dependencies and vitest cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            .pnpm-store
            node_modules/.vitest
      - run: pnpm run build # ensures TS build output for correct test imports
      # Run partial test pass on PRs (only changed or dependent packages)
      - name: Run affected tests
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "ğŸ§© Running 'test' script in changed or dependent packages..."
          pnpm --filter "...[origin/main]" test
      # On main, run the full test suite w/ type checking
      - name: Run full test suite
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "ğŸ§ª Running full test suite on main..."
          pnpm run test

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
